run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck
    - gosec
    - golint
    - unmarshal
    - noctx
    - errname

linters-settings:
  gofmt:
    simplify: true
  gosec:
    excludes:
      - G104

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0